; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Picchooser"
#define MyAppVersion "1.3"
#define MyAppPublisher "魏子昂软件工作室"
#define MyAppURL "https://github.com/WZA-Leon/Picchooser"
#define MyAppExeName "picc.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5B74FB9E-281F-4C4A-A672-5498F8DF0510}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={localappdata}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=.\LICENSE
; 安装到用户 AppData，无需管理员权限（仅当前用户）
PrivilegesRequired=lowest
OutputDir=.\dist
OutputBaseFilename=piccsetup
SetupIconFile=.\icon.ico
SolidCompression=yes
WizardStyle=modern dynamic windows11

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "simplechinese"; MessagesFile: "compiler:Languages\Simple Chinese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; 启动器（C++ 编译产物，负责首次运行时下载嵌入式运行时并启动主程序）
Source: "{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; 运行时引导脚本（首次运行下载 Python 嵌入式运行时 + 安装依赖 + 配置 Tkinter）
Source: "bootstrap_runtime.ps1"; DestDir: "{app}"; Flags: ignoreversion
Source: "bootstrap_runtime.bat"; DestDir: "{app}"; Flags: ignoreversion
; 嵌入式运行时（含提取好的 tkinter 组件；首次运行若缺失会由引导脚本下载补齐）
Source: "runtime\*"; DestDir: "{app}\runtime"; Flags: ignoreversion recursesubdirs createallsubdirs
; 程序源码（由嵌入式运行时解释执行，无需 PyInstaller 打包）
Source: "Picchooser.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "PicchooserGUI.py"; DestDir: "{app}"; Flags: ignoreversion
; 原生缩略图 DLL（GUI 用；缺失时 GUI 会自动回退到 Pillow 缩放）
Source: "thumbnail\thumbnail.dll"; DestDir: "{app}\thumbnail"; Flags: ignoreversion
Source: "photo_config.json"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
; 安装时把安装目录加入用户 PATH（卸载时自动移除）
Root: HKCU; Subkey: "Environment"; ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}"; Check: NeedsAddPath('{app}')

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
const
  EnvironmentKey = 'Environment';
  WM_SETTINGCHANGE = $001A;
  SMTO_ABORTIFHUNG = $0002;

var
  { 安装开始时 PATH 是否已包含安装目录 }
  PathWasPresent: Boolean;

{ SendMessageTimeout 不在 Pascal Script 内置函数中，需自行从 user32.dll 导入 }
function SendMessageTimeout(hWnd: HWND; Msg: Cardinal; wParam: Cardinal;
  lParam: Integer; fuFlags: Cardinal; uTimeout: Cardinal;
  var lpdwResult: Cardinal): Cardinal;
  external 'SendMessageTimeoutW@user32.dll stdcall';

{ 判断 PATH 中是否已包含指定目录（忽略大小写、忽略结尾反斜杠、按分号逐项比较） }
function IsDirInPath(const Dir: string): Boolean;
var
  PathValue: string;
  Remaining: string;
  Current: string;
  SepPos: Integer;
  Target: string;
begin
    Result := False;
  if not RegQueryStringValue(HKCU, EnvironmentKey, 'Path', PathValue) then
    Exit;

  { 去掉结尾反斜杠后比较，避免 "C:\App" 与 "C:\App\" 被当成两个目录 }
  Target := RemoveBackslashUnlessRoot(Dir);

  Remaining := PathValue + ';';
  while Remaining <> '' do
  begin
    SepPos := Pos(';', Remaining);
    if SepPos = 0 then
      Break;
    Current := Trim(Copy(Remaining, 1, SepPos - 1));
    Delete(Remaining, 1, SepPos);
    if (Current <> '') and
       (CompareText(RemoveBackslashUnlessRoot(Current), Target) = 0) then
    begin
      Result := True;
      Exit;
    end;
  end;
end;

{ [Registry] 条目的条件：PATH 中还没有该目录时才写入，避免重复安装时重复追加 }
function NeedsAddPath(Param: string): Boolean;
begin
  Result := not IsDirInPath(Param);
end;

{ 广播 WM_SETTINGCHANGE，让已打开的进程（资源管理器、新开的终端）立即感知 PATH 变化 }
procedure BroadcastEnvironmentChange;
var
  ResultCode: Cardinal;
begin
  SendMessageTimeout(HWND_BROADCAST, WM_SETTINGCHANGE, 0, 0,
    SMTO_ABORTIFHUNG, 5000, ResultCode);
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssInstall then
  begin
    { 安装前记录 PATH 是否已包含安装目录，用于判断本次是否真的改动了 PATH }
    { 注意：app 常量在 InitializeSetup 阶段尚未初始化，必须在 ssInstall 时才能展开 }
    PathWasPresent := IsDirInPath(ExpandConstant('{app}'));
  end
  else if (CurStep = ssPostInstall) and (not PathWasPresent) and
     IsDirInPath(ExpandConstant('{app}')) then
  begin
    { 只有本次新加入了 PATH 才需要广播；重复安装且已存在时无需打扰系统 }
    BroadcastEnvironmentChange;
  end;
end;


